# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cnvrt <- function(input, inputType, outputType) {
    .Call(`_cheminf_cnvrt`, input, inputType, outputType)
}

#' Convert SMILES to molecular formula
#' @description convert a smile to a molecular formula
#' @param smile a valid SMILE
#' @examples
#' smilesToMF(amino_acids$SMILES[1])
#' @export
smilesToMF <- function(smile) {
    .Call(`_cheminf_smilesToMF`, smile)
}

#' Convert SMILES to accurate mass
#' @description convert a smile to an accurate mass
#' @param smile a valid SMILE
#' @examples
#' smilesToAccurateMass(amino_acids$SMILES[1])
#' @export
smilesToAccurateMass <- function(smile) {
    .Call(`_cheminf_smilesToAccurateMass`, smile)
}

#' SMARTS substructure search
#' @description SMARTS substructure searching for SMILES.
#' @param smile a valid SMILE
#' @param smart a valid SMARTS symbol
#' @examples
#' smartsSearch(amino_acids$SMILES[1],"[OX2H]")
#' @export
smartsSearch <- function(smile, smart) {
    .Call(`_cheminf_smartsSearch`, smile, smart)
}

descriptor <- function(smile, desc) {
    .Call(`_cheminf_descriptor`, smile, desc)
}

